--To optimize inventory management using the "Online Retail" dataset, 
--we used SQL queries to extract relevant information and generate insights.
--Here are some example queries:

--Calculate the total quantity sold for each product:
SELECT StockCode, SUM(Quantity) AS TotalQuantitySold
FROM OnlineRetail
GROUP BY StockCode

--Identify the top-selling products:
SELECT top 5 StockCode, Description, SUM(Quantity) AS TotalQuantitySold
FROM OnlineRetail
GROUP BY StockCode, Description
ORDER BY TotalQuantitySold DESC

--Determine the slow-moving or low-demand products:
SELECT StockCode, Description, SUM(Quantity) AS TotalQuantitySold
FROM OnlineRetail
GROUP BY StockCode, Description
HAVING SUM(Quantity) < 50

--Calculate the total revenue generated by each product:
SELECT StockCode, Description, SUM(Quantity*UnitPrice) AS TotalRevenue
FROM OnlineRetail
GROUP BY StockCode, Description
ORDER BY TotalRevenue DESC


--Analyze sales trends over time:
SELECT YEAR(InvoiceDate) AS Year, MONTH(InvoiceDate) AS Month, SUM(Quantity) AS TotalQuantitySold
FROM OnlineRetail
GROUP BY YEAR(InvoiceDate), MONTH(InvoiceDate)
ORDER BY Year, Month

--Calculate the inventory turnover rate for each product:
SELECT StockCode, Description, (SUM(Quantity) / COUNT(DISTINCT InvoiceNo)) AS InventoryTurnoverRate
FROM OnlineRetail
GROUP BY StockCode, Description
ORDER BY InventoryTurnoverRate DESC

--These queries provide insights into product sales, revenue, profitability, demand trends, and inventory turnover.
--By analyzing this information, businesses can identify popular products, slow-moving items, profitable products,
--and make data-driven decisions to optimize inventory management, such as adjusting stocking levels, identifying underperforming products, and focusing on high-demand items.

